### PR TITLE
Imgui update

### PR DESCRIPTION
**Pull request by drillsar**
Updates imgui to tree 6e8579fc144f1d59a75aabf3740470d3e3739a1b; Anything after this tree will need to change GetInternalState functions, etc(). When I have time will look at changing those functions. Referenced Issue #746

### CODE REVIEW

**Comment by BBMempire11** [comment]
where do i download

**Comment by drillsar** [comment]
@BBMempire11 for the latest release:
https://ci.appveyor.com/project/benvanik/xenia/build/1.0.846-master/job/d1jym5qxnqv947k4/artifacts

**Comment by Oreos019** [comment]
merged
image

**Comment by Margen67** [comment]
This should be closed. #1383 updates to a newer version.

**Pull request closed without merging**
