### PR TITLE
[Kernel] Add PVR opcode (includes cvars support)

### PR DESCRIPTION
**Pull request by halotroop2288**
Adds the PVR opcode to the list of recognized opcodes. Includes useful comments.

***Revival of #1464 (deleted fork)***

### CODE REVIEW

**Comment by Triang3l** [comment]
Please squash two commits into a single one, and run `xb format` between `git add` and `git commit` to ensure style consistency in the code, including correct line widths. Also, the meanings of the specific values are still missing from the cvar description.

**Comment by halotroop2288** [comment]
image

**Comment by Triang3l** [comment]
> image

It needs to be executed after adding the modified files to Git staging — it only formats the files that are displayed as green in `git status`.

**Comment by halotroop2288** [comment]
> It needs to be executed after adding the modified files to Git staging — it only formats the files that are displayed as green in `git status`.

I know. There were no changes needed when I was done.

**Comment by gibbed** [comment]
You can do `xb format --all` I think (at least `xb lint` has that option). Though it may result in unrelated files to this commit being formatted.

**Comment by JoelLinn** [comment]
We use `clang-format` version 13. There will be subtle differences with older versions.

**Comment by halotroop2288** [comment]
@Triang3l Have I satisfied your request?

**Comment by halotroop2288** [comment]
*ahem* This is ready for review...

**Pull request merged**
