### PR TITLE
Update Vulkan BufferCache Capacity

### PR DESCRIPTION
**Pull request by allens39**
Should fix missing graphics in issues #1187, #123, and #745

### CODE REVIEW

**Comment by gibbed** [comment]
This will only hide whatever the issue actually is. The Xbox 360 only has 512MB of RAM, so having a buffer be 512MB is overkill.

**Comment by allens39** [comment]
@gibbed where would the issue lie then? I also dont understand how having a buffer be the size of the xbox 360 ram would be an issue for an emulator trying to get it to work on PCs.

**Comment by Irixion** [comment]
Wouldn't having a large buffer size improve performance anyhow? What of having it as a temporary workaround?

**Comment by gibbed** [comment]
@allens39 The issue lies in that a real 360 wouldn't be able to exhibit the behavior games are doing currently if increasing the buffer size is improving it, so the underlying issue needs to be researched and understood instead of mitigating the issue without understanding it.

**Pull request closed without merging**
