### PR TITLE
[APU] XMA: Fix audio loop handling

### PR DESCRIPTION
**Pull request by Pseudo-Kernel**
This PR fixes the audio loop handling issue (#1515).

In game 435A07E7 (English title: Dodonpachi Saidaioujou) also have same issue when playing the background music.
After fix, i tested (on game 435A07E7) and it seems to work fine.

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
Fixes broken sound loops (engine and loading sound effects) in Midnight Club: Los Angeles.

**Comment by Tervel1337** [comment]
Fixes broken loop sounds in GTA V. Same thing for broken car sounds in GTA IV.

**Comment by SonofUgly** [comment]
Causes really bad buzzing in Ace Combat 6. [Log](https://www.mediafire.com/file/jfmj4irkgwngdu9/xenia+ac6+1808.7z/file)

**Comment by Pseudo-Kernel** [comment]
> Causes really bad buzzing in Ace Combat 6. [Log](https://www.mediafire.com/file/jfmj4irkgwngdu9/xenia+ac6+1808.7z/file)

I found that buzzing sound is caused when loop_start == loop_end == 0 and loop_count == 0xff (in Ace Combat 6).
Checking loop_start < loop_end when setting next loop fixes buzzing, but need to handle additional cases like loop_start > loop_end.

**Comment by Gliniak** [comment]
Can you cleanup this PR? Squash these commits to be commited as one

**Comment by Pseudo-Kernel** [comment]
> Can you cleanup this PR? Squash these commits to be commited as one

Cleanup finished.

**Comment by reditec** [comment]
Please merge this! This fix is important for MANY games

**Comment by illusion0001** [comment]
Reeebase

**Comment by lKomus** [comment]
What's preventing this to get merged?

**Pull request merged**
