### PR TITLE
Update utf8.cc

### PR DESCRIPTION
**Pull request by Hadrianneue**
~~edit: idk what im doing help ;D~~
fixes building on linux.

### CODE REVIEW

**Comment by Triang3l** [comment]
Hello, thank you for this pull request! Please run `git-clang-format` (`xb format`) after `git add`ing files and before `git commit`ting so the list of included files is sorted properly, and add the subsystem prefix — in this specific commit, `[Base] `, to the beginning of the commit message. You can modify the existing commit via `git commit --amend` or by reverting it via `git reset HEAD~1` and creating it again.

**Comment by Hadrianneue** [comment]
> Hello, thank you for this pull request! Please run `git-clang-format` (`xb format`) after `git add`ing files and before `git commit`ting so the list of the included header files is sorted properly, and add the subsystem prefix — in this specific commit, `[Base] `, to the beginning of the commit message. You can modify the existing commit via `git commit --amend` or by reverting it via `git reset HEAD~1` and creating it again.

i'm sorry i did a pull request by mistake lol, i was trying to build it on linux with the aur script, this is more of a workaround than a proper fix, i won't proceed with this PR, sorry to bother really, have a good one

**Comment by Triang3l** [comment]
No, it's a proper fix, this file uses `uint32_t` for purposes within the file itself, `<cstdint>` needs to be included — just preserving alphabetical order within that group of `#include`s.

**Comment by Margen67** [comment]
@Triang3l Looks like you forgot to review my PR: #2209
Any chance you could look at it soon? Thanks.

**Comment by Hadrianneue** [comment]
@Triang3l i'm not sure what i did here since i don't really use github or CI (its pending for several hours).

**Pull request merged**
