### PR TITLE
[Vulkan] Use Format

### PR DESCRIPTION
**Pull request by NekokoTime**
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkFormat.html

### CODE REVIEW

**Comment by gibbed** [comment]
Are you guessing at this or have you seen games use these?

**Comment by NekokoTime** [comment]
@gibbed I am ah suppose and following Vulkan's Link

**Comment by gibbed** [comment]
I don't think we need to define mappings for texture formats unless we know of a game that wants to use it. @DrChat?

**Comment by gibbed** [comment]
Actually, the mappings you've defined are incorrect to begin with.

**Pull request closed without merging**
