### PR TITLE
Fix SHA1 and SHA256 state endianness

### PR DESCRIPTION
**Pull request by CookiePLMonster**
Fixes malfunctioning SHA256 hash, corrupting its state between Update and Finish calls.

**Some** code paths were performing byteswapping from host to guest endianness (`XeCryptSha256Init`), but some were not (`XeCryptSha256Update`, `XeCryptSha256Final`), so SHA256 object was left in a corrupted state and hashing yielded wrong results.

Huge thanks to @Gliniak who scanned the logs and identified SHA256 functions as a possible culprit - I'd spend hours looking into I/O functions otherwise :)

Makes Forza Horizon go ingame:
image

**Question:** I have similar doubts about DES3 where `XECRYPT_DES_STATE` contains `uint32_t`'s in host endianness, but it's a guest structure. However, I'm not sure what's their true data type - they're defined as
```
uint32_t keytab[16][2];
```

but the way DES3 uses those fields implies it's an array of `uint64_t`'s.

### CODE REVIEW

**Comment by gandalfthewhite19890404** [comment]
Causes MGS2/3 hang at selection screen.

**Comment by CookiePLMonster** [comment]
> Causes MGS2/3 hang at selection screen.

Can you post logs (with level 3) from both **without** and **with** this PR? Assuming I implemented everything correctly this PR is nearly impossible to cause regressions, as it fixes something which can be trivially proven to be a bug. It's possible that hashing working correctly unlocked some other broken code path for those games.

**Comment by gandalfthewhite19890404** [comment]
> > Causes MGS2/3 hang at selection screen.
> 
> Can you post logs (with level 3) from both **without** and **with** this PR? Assuming I implemented everything correctly this PR is nearly impossible to cause regressions, as it fixes something which can be trivially proven to be a bug. It's possible that hashing working correctly unlocked some other broken code path for those games.

Sorry, it was my mistake, I'll delete my post.

**Comment by CookiePLMonster** [comment]
I have force pushed a fix for SHA1 implementation, existing one was incorrectly promoting bytes to dwords and was writing past the array.

This prepares for an upcoming PR getting Forza Horizon 2 to work.

**Pull request merged**
