### PR TITLE
Added Missing LICENSE for dlmalloc

### PR DESCRIPTION
**Pull request by p01arst0rm**
The License for the dlmalloc dependency currently does not have a license included alongside the file; add the license file for the dlmalloc project (Creative Commons Zero 1.0 Universal)

### CODE REVIEW

**Comment by Razzile** [comment]
Good spot. I don't have merge powers unfortunately.

**Comment by Triang3l** [comment]
Where are we using dlmalloc at this point? :o

**Comment by Gliniak** [comment]
Seems like it is unused and can be removed. 
I've just build Xenia (at least on windows) with success without it

**Comment by p01arst0rm** [comment]
quite possible, ive noticed theres a couple orphaned dependencies through reviewing the buildsystem recently

**Pull request closed without merging**
