### PR TITLE
Update download.md

### PR DESCRIPTION
**Pull request by Margen67**
So noobs stop asking where D3D12 builds are..

### CODE REVIEW

**Comment by DrChat** [comment]
This was changed to the current link in the first place because artifacts from pull requests show on that page - which can allow a malicious user to plant a new build.

**Comment by Margen67** [comment]
@DrChat I made it a direct link.

**Comment by DrChat** [comment]
Nope - that's just to the artifacts page, which shows artifacts from any build - not any specific branch.
[Here's](https://ci.appveyor.com/api/projects/benvanik/xenia/artifacts/xenia-master.zip?branch=d3d12&job=Configuration%3A%20Release) a direct link to d3d12 - give those to people when they ask. Otherwise, the branch isn't ready for release.

**Comment by Margen67** [comment]
My commit isn't showing up on this PR (possibly because it's closed)
https://github.com/Margen67/xenia/commit/75a0b3eb2f0b38cb52c042712c7f06edd52ba016

**Comment by Margen67** [comment]
@DrChat It may not be ready for release, but it's much further than Vulkan.
Can we please just add a direct link to D3D12, and Master so noobs stop getting confused and asking on the Discord?

**Comment by Wildenhaus** [comment]
May I suggest using a GitHub Release for milestones? It would alleviate linking directly to the AppVeyor and potentially having malicious builds while making it easier for people to find a relatively stable build.

**Pull request closed without merging**
