### PR TITLE
README.md: add build instructions for GNU/Linux

### PR DESCRIPTION
**Pull request by Hi-Angel**
Signed-off-by: Konstantin Kharlamov <Hi-Angel@yandex.ru>

### CODE REVIEW

**Comment by gibbed** [comment]
This is a good idea for when we have a functioning Linux build, until then we don't need be providing instructions on it here.

Can be revisited in the future.

**Comment by Hi-Angel** [comment]
FWIW, before writing these instructions I tested that these commands work for me.

**Comment by gibbed** [comment]
It's not that these instructions are wrong, it's that the Linux build isn't usable by anyone other than those who are working on getting the Linux build functional.

IE: this would advertise that we supposedly have functioning Linux support if it were to be added.

**Comment by Margen67** [comment]
Maybe the Linux building instructions in building.md should be changed instead?
they might be outdated.

**Comment by gibbed** [comment]
That would be more sensible, though making those changes should probably wait until #1392 is merged.

**Comment by illusion98** [comment]
https://github.com/xenia-project/xenia/pull/1392 is now merged.

**Comment by Margen67** [comment]
@Hi-Angel Any update on this?

**Comment by Hi-Angel** [comment]
Sorry, yeah, so, @gibbed @Margen67 what's the decision on this, should I change the description in `docs/building.md` file instead?

**Comment by Hi-Angel** [comment]
> It's not that these instructions are wrong, it's that the Linux build isn't usable by anyone other than those who are working on getting the Linux build functional.
>
> IE: this would advertise that we supposedly have functioning Linux support if it were to be added.

You know, I think I could just add a note that the GNU/Linux build is strictly experimental, and there's some functional still missing. What do you think?

**Comment by Margen67** [comment]
> 
> 
> Sorry, yeah, so, @gibbed @Margen67 what's the decision on this, should I change the description in `docs/building.md` file instead?

Yes.

**Comment by Hi-Angel** [comment]
Okay, so, I'm sorry, I'll probably close this for now. From the review comments it's clear that the changes need to be remade. I looked at the current `docs/building.md`, it has outdated information *(it says Mesa doesn't support 4.5, which long hasn't been true)*, besides I don't have Ubuntu *(I'm personally using Archlinux, and to other people I usually recommend Fedora)*, so overall quite a bit of background work is needed to fix the docs. And I'm a bit short on spare time right now.

Maybe I'll make another pull some time later… I'm definitely okay though if somebody beats me to it :)

**Comment by Hi-Angel** [comment]
> it says Mesa doesn't support 4.5, which long hasn't been true

Ah, I stand corrected, I was looking at the outdated file as well :) Anyway…

**Pull request closed without merging**
