### PR TITLE
Clean up .appveyor.yml

### PR DESCRIPTION
**Pull request by Margen67**
Changes:
* Removed comments
* Changed `version` into `'{build}-{branch}'` since xenia doesn't really have a version number.
* Removed unneeded/unused stuff:
  * `clone_folder` (it defaults to `c:\dev\xenia` anyway)
  * environment variables (leftovers from example yml)
  * Removed `cmd: set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%` from `install`
  * Removed `.bat` from `xb`
  * Removed `Platform: Windows` and replaced `%PLATFORM%` with `Windows` since the steps that use it are only for Windows. Proper cross-platform support might require this: https://www.appveyor.com/docs/build-configuration/#specializing-matrix-job-configuration (not that it matters since Linux on master is broken, and the linux branch is outdated)
* Put `after_build` in proper order and made it use AppVeyor's multi-line syntax.

### CODE REVIEW

**Comment by illusion98** [comment]
😕 why closed?

**Comment by gibbed** [comment]
It was four folders deep because of how he changed the add paths on `7z`.

@Margen67 Does AppVeyor support the versioning scheme you wanted to do here without barfing?

**Comment by Margen67** [comment]
It might be doing that since it's a PR. This is how it looks on my AppVeyor: https://ci.appveyor.com/project/Margen67/xenia/builds/26130674

**Comment by gibbed** [comment]
I don't think changing it away from the automated versioning is any different than using the build number. They both mechanically work the same. One looks nicer (version numbers).

We could just add the version number stuff from AppVeyor into the UI as well?

**Comment by Margen67** [comment]
Maybe, but I don't know how to do that.
Also, are these lines necessary? https://github.com/xenia-project/xenia/blob/master/.appveyor.yml#L40-#L41

**Comment by gibbed** [comment]
For safety, yes.

**Comment by Margen67** [comment]
@gibbed GitHub won't let me reopen this. Can I make a new PR?

**Comment by gibbed** [comment]
Yeah that's fine. I can add new comments there.

**Pull request closed without merging**
